### ISSUE TITLE
Rendering an Inky Partial Escapes the Content

### ISSUE THREAD

**Issue by keokilee** [zurb/inky-rb#10]
When I try to render an Inky partial within an Inky template, the partial's content is escaped.

Here's my email template (test_mail.html.inky):

```
<div>
  <%= render 'inky_partial' %>
  Main content
</div>
```

And here's my partial template (_inky_partial.html.inky):

```
<div>partial content</div>
```

And here's a screenshot from ActionMailer::Preview:
<img width="768" alt="screen shot 2016-07-07 at 9 26 35 am" src="https://cloud.githubusercontent.com/assets/191770/16666906/6dc9c11a-4425-11e6-86d7-a3c0ad7811d0.png">

For now, I've been calling `.html_safe` on the rendered partial. Would the fix be to just append that to the output of `Inky::Core.re_inject_raws `?

**Comment by codergeek121** [comment]
If you change the partial to a regular html.erb it should work as expected. Even if you have inky language in the partial
