### ISSUE TITLE
Columns align attributes does not seem to be rendered

### ISSUE THREAD

**Issue by bobmaerten** [zurb/inky-rb#13]
As specified in the [inky documentation](https://foundation.zurb.com/emails/docs/alignment.html#vertical-alignment), you can add `valign` to a column definition to change vertical alignement, but it's not rendered as expected in the html output.

    <columns small="10" large="10" align="right" valign="middle">...</columns>

is rendered to

    <th class="small-10 large-10 columns last" align="left">...</th>

**Comment by kball** [comment]
Thanks for the bug report! I'll probably get a chance to dig into this in the next couple of weeks, but would happily accept a PR if you have time to work on it before then.  My recommended approach would be to add a spec for exactly this case to spec/grid_spec.rb, and then start tinkering around in the `_transform_columns` method of component_factory.rb

**Comment by marcandre** [comment]
Fixed, yay
