### ISSUE TITLE
Support other templates and/or chaining?

### ISSUE THREAD

**Issue by bobmaerten** [zurb/inky-rb#14]
Do you think it would be possible to use other templating languages like [Slim](http://slim-lang.org) or Markdown and by the way support chaining (i.e. `file.html.inky.slim`)?

Currently we set a guard-shell to render our slim files to ERB, but I found with replacing `:erb` by  `:slim` in the [`lib/inky/rails/template_handler.rb`](https://github.com/zurb/inky-rb/blob/v1.3.6.1/lib/inky/rails/template_handler.rb#L5) file would potentially enable inky files to parse slim templates, that would fit nicer in our workflow. Clearly template chaining would be a better option.

**Comment by sumitngupta** [comment]
+1 though we use haml

**Comment by kball** [comment]
@bobmaerten Great question! I didn't see an obvious way to do chaining in the html rendering pipeline for rails (asset pipeline does it out of the box, but I couldn't find any examples for how to do it for HTML... looking at e.g. the haml extension just showed examples of doing 1.  To get the first version out I forced in ERB as the default to catch most cases, but I agree that chaining would be the best option.

I'll be happy to dig in more when I have time; if you know of any good examples that do this, please point me to them.

Or alternatively, if you want to tackle this, I'd be very happy to accept a PR.

**Comment by marcandre** [comment]
See #37 and #38. Comments welcome before I merge them.
