### ISSUE TITLE
Partial render isn't working 

### ISSUE THREAD

**Issue by dofu** [zurb/inky-rb#18]
My email consist of a footer which doesn't seem to render out properly. 
The output is still Inky's templating language instead of complex tables.

< row>
<%= render partial: 'layouts/footer', locals: {country: @country} %>
< /row>
How does one handle partial render? I have tried renaming the file to 'inky' and it doesn't seem to do anything.

I've tried renaming my partials to inky as well.

**Comment by kball** [comment]
Interesting, I'll take a look... can you give me a little more detail on the set of files and their name extensions? It looks like both the rendering page and the partial are in inky?  Is that correct?

**Comment by redroot** [comment]
I've had a similar issue, inside  a top level view a render command like the below

```<%= render partial: 'user_mailer/campaign_listed', locals: { campaign: campaign, utm_query_params: utm_query_params } %>```

will print raw <table> etc tags. `<table class='row campaign-listed'><tbody><tr> <th class='small-12 large-4 columns last first'><table><tr><th>...`. Ive tried other ERB opening tags but it doesn't seem to make a difference. Any ideas?

**Comment by dofu** [comment]
I use raw(...) on the partial itself and it works just fine. 
its another option apart from html.safe
