### ISSUE TITLE
Center tag is problematic in safari and iphone

### ISSUE THREAD

**Issue by AvanthikaMeenakshi** [zurb/inky-rb#20]
I have an image tag inside center tag, which is left aligned in safari and iphone. In chrome, inbox and gmail mail, it is perfectly okay! Can you check this issue and get back? Here's my code snippet.

`<wrapper class="Mail-Header">
  <container class="Border-Mail">
    <spacer size="20"></spacer>
    <row>
      <columns small="12" align="center">
        <center>
          <a href="http://allt.in/" target="_blank">
          <img src="logo.png" alt="lorem Ipsum" width="122px" height="35px" class="Allt--Logo-Mailer" />
          </a>
        </center>
      </columns>
    </row>
    <spacer size="20"></spacer>
  </container>
</wrapper>`

**Comment by keokilee** [comment]
I had this issue too, although I was using a `link_to` helper to insert the image into my link. I fixed it by moving the center tags inside of the `a` tag. It's not great, but it should center align things in Apple Mail.

**Comment by marcandre** [comment]
I wanted to check if this was an issue with the gem (`inky-rb`) or the library (`inky` & foundation for emails).

There's currently a discrepancy with the outputs that I hope to fix soon (see #32), with a bit of luck that should resolve your issue, otherwise this will have to be opened with `inky`.

**Comment by marcandre** [comment]
I can confirm that `inky-rb` I just released [1.3.7.0](https://github.com/zurb/inky-rb/tree/v1.3.7.0) has a different output now and I believe you should be ok with it. Let us know if that's not the case. Thanks for reporting this! :smile:
