### ISSUE TITLE
Allow sass variables to be used alongside inky-rb

### ISSUE THREAD

**Issue by seanrankin** [zurb/inky-rb#26]
It would be super-awesome to be able to use the foundation for emails sass variables within inky-rb.

**Comment by bobmaerten** [comment]
It is!
Use your classic `<%= stylesheet_link_tag "mailer" %>` link in your mailer layout, use your sass variables in `mailer.sass`, and let `premailer_rails` gems inline-all-the-thing within your mails.

**Comment by zion** [comment]
So If I wanted to override the default colors of the buttons, would I do: 

```@import "foundation-emails";
$button-background: #8bc53f;```

in the `mailer.scss` file? and include that in the inky layout?

**Comment by marcandre** [comment]
Define your variable before the `@import`

**Comment by zion** [comment]
I tried that, but it wasn't working. I ended up creating an _settings.scss with all the defaults and just added an import for the settings. 

Thanks! Really liking inky

**Comment by marcandre** [comment]
Not sure what to tell you @zion, it works well for me (Rails 4.2, Sass 3.4.22)

**Comment by zion** [comment]
No worries! I like having all the settings to change anyway. Thanks for the reply
