### ISSUE TITLE
Parsing issue :: Missing end tag for 'br' (got "p")

### ISSUE THREAD

**Issue by anthony-robin** [zurb/inky-rb#28]
I'm using inky-rb gem in my Rails project and I get an error while previewing my mailer: 
`Missing end tag for 'br' (got "p")`.

My mail content is `<p>Lorem ipsum <br> dolor sit amet</p>`. 
I discovered if I remove the `<br>` tag it works, if I add a slash before the end of the closing tag (`<br />`) it works as well. 

So, my guess is that the parser is panicked when it find an html tag without slash.
How can I avoid getting this error (I'm not sure if this issue comes from this gem or from nokogiri) in my mailer ?

My stack: 
- Rails 4.2.7.1
- Ruby 2.3.0
- Inky-rb 1.3.6.1

**Comment by seanrankin** [comment]
I'm running into the same issue. Any way to make Inky not-so-sensitive?

**Comment by marcandre** [comment]
At first sight, looks like the same issue as #29

**Comment by marcandre** [comment]
Should be completely addressed with [1.3.7.0](https://github.com/zurb/inky-rb/tree/v1.3.7.0). Let us know if that's not the case! Thanks for reporting this.

**Comment by seanrankin** [comment]
Sweet.

**Comment by varun-raj** [comment]
This happens for image as well.

**Comment by marcandre** [comment]
@varun-raj: This is fixed in 1.3.7.0.

**Comment by marcandre** [comment]
@varun-raj: This is fixed in 1.3.7.0.
