### ISSUE TITLE
Nokogiri::XML problem?

### ISSUE THREAD

**Issue by joenoon** [zurb/inky-rb#29]
I had to change `Nokogiri::XML` to `Nokogiri::HTML` as a quick fix in my fork to prevent links in my emails getting munged.  Not sure if this is a known issue or the right fix, but wanted to open a conversation about it:

```
x = "<button class=\"radius\" href=\"https://www.google.com/test?a=1&b=2&c=3\">Foo</button>"

irb(main):018:0> puts Nokogiri::XML(x)
<?xml version="1.0"?>
<button class="radius" href="https://www.google.com/test?a=1=2=3">Foo</button>
=> nil

irb(main):019:0> puts Nokogiri::HTML(x)
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><button class="radius" href="https://www.google.com/test?a=1&amp;b=2&amp;c=3">Foo</button></body></html>
=> nil
```

**Comment by marcandre** [comment]
Should be completely addressed with [1.3.7.0](https://github.com/zurb/inky-rb/tree/v1.3.7.0). Let us know if that's not the case! Thanks for reporting this.
