### ISSUE TITLE
Templates render _only_ the style node

### ISSUE THREAD

**Issue by sdhull** [zurb/inky-rb#35]
Am I doing something obviously wrong?

Site is open source, feel free to check it out. Branch is [here](https://github.com/sdhull/strategic_voting/tree/match-email-and-messaging). When I visit the email preview (or send the email from console), the resulting email has the email layout and the `<style>` node from the template but nothing else.

What gives? I even tried updating to use latest master from github. I also had [an issue](https://github.com/zurb/foundation-emails/issues/609) with compatibility of `foundation-rails` and `foundation-emails`.

**Comment by marcandre** [comment]
Sorry about that... It's a bug that happens for layouts with more than one node.

It should be fixed in the next few days, [this commit](https://github.com/zurb/inky-rb/commit/19d8f839bc24505a28c937b533e26f2eeecf0088) in #32 addresses that. Feel free to try that branch if you want in the meantime...

I'll close this issue when I release it.

**Comment by marcandre** [comment]
Should be completely addressed with [1.3.7.0](https://github.com/zurb/inky-rb/tree/v1.3.7.0). Let us know if that's not the case! Thanks for reporting this.

**Comment by sdhull** [comment]
Looks like this fixes the issue! Thank you!

**Comment by sdhull** [comment]
So what I found tonight is that while this appeared to work properly in my local dev environment, it's not working for me on my staging environment on Heroku...

**Comment by marcandre** [comment]
@sdhull Probably an issue with deploying?
From the Ruby console, check the result of `Inky::Rails::VERSION`

**Comment by sdhull** [comment]
Yeah, I thought it was maybe something like that too, however from heroku console:
```
irb(main):008:0> Inky::Rails::VERSION
=> "1.3.7.0"
```

When I try to send emails from the console, inky templates don't send at all. When I inspect the mail object returned, the body is `nil`.

```
irb(main):005:0> mail.html_part
=> nil
```

But emails with just html templates send fine (I haven't converted existing templates to inky).

**Comment by marcandre** [comment]
Mmm, so it's not the same bug (the `<style>` used to render), right?

Ideally open a new issue, but I won't be able to check it out let alone fix it unless you manage to dig a bit further. The gem is quite small, and there's a rails test so maybe you can figure out what's causing the issue?

**Comment by sdhull** [comment]
Figured it out. Submitted a PR to fix it.

**Comment by marcandre** [comment]
Probably an issue with deploying?
From the Ruby console, check `Inky::Rails::VERSION`

**Comment by sdhull** [comment]
lol sorry I sent that last Friday while Dyn was under attack. When Dyn had recovered I just came to Github and left the comment. Apparently the DDoS attack delayed the processing of this email. You can ignore this, sorry.
