### ISSUE TITLE
Inky 1.3.7.0 - Nokogiri - Heroku issue

### ISSUE THREAD

**Issue by Ceda** [zurb/inky-rb#40]
After updating to 1.3.7.0 have problem on Heroku with Nokogiri.
[html.elements](https://github.com/zurb/inky-rb/blob/develop/lib/inky.rb#L36) return empty array and inky template is't processed.
When replace html.elements with html.children, work well.

In development on localhost everything ok.

Probably problem with libxml2 on heroku.

```ruby 
rails (5.0.0.1)
nokogiri (1.6.8.1)
```

@marcandre ?

**Comment by marcandre** [comment]
Right, this has [been reported](https://github.com/zurb/inky-rb/pull/39), would either you or @sdhull report this to heroku so they can fix it?

I guess I'll have to merge @sdhull's hack :-(

**Comment by sdhull** [comment]
OK, opening a support ticket with Heroku

**Comment by sdhull** [comment]
In the meantime @Ceda feel free to point to my branch which works on heroku:

```
gem 'inky-rb', require: 'inky', github: "sdhull/inky-rb", branch: "fix-heroku"
```

**Comment by sdhull** [comment]
OK I've opened a ticket with heroku. Unfortunately their system is designed to have issues be private so I can't share a link.

**Comment by marcandre** [comment]
Release 1.3.7.1, which should address it. Thanks for the bug report

**Comment by juliosantos** [comment]
To whomever may end up here.

There's other instances of `children` vs `elements` which aren't addressed yet. Heroku's `heroku-16` stack includes an updated `libxml2` package. Changing the stack (`heroku stack:set heroku-16`) fixes this.

**Comment by marcandre** [comment]
@juliosantos Thanks. We've bypassed the issue by using `children` instead.
