### ISSUE TITLE
Undefined Method in Install Generator

### ISSUE THREAD

**Issue by bartboy011** [zurb/inky-rb#41]
Hey folks, thanks for making this! Very glad to see that the day I start using this is the day after a release that now works with Heroku! Very cool. 

Here's the issue I'm hitting. I'm running the `rails g inky:install` command and getting this exception:

`(erb):7:in 'template': undefined method 'stylesheet_link_tag' for #<Inky::Generators::InstallGenerator:0x007fb79c631b80> (NoMethodError)`
`Did you mean?  stylesheets_base_dir`

I can provide a full error stack if you'd like it, but here's the last few lines (with full paths shortened for clarity):

```
from ~/lib/ruby/2.3.0/erb.rb:864:in `eval'
from ~/lib/ruby/2.3.0/erb.rb:864:in `result'
from ~/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:116:in `block in template'
from ~/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `render'
from ~/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `block (2 levels) in invoke!'
from ~/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `open'
from ~/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `block in invoke!'
from ~/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `invoke_with_conflict_check'
from ~/gems/thor-0.19.1/lib/thor/actions/create_file.rb:60:in `invoke!'
from ~/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
from ~/gems/thor-0.19.1/lib/thor/actions/create_file.rb:25:in `create_file'
from ~/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:115:in `template'
from ~/bundler/gems/inky-rb-f22a35fc220c/lib/generators/inky/install_generator.rb:24:in `create_mailer_layout'
```

Here's what's happening leading up to this:

```
Running via Spring preloader in process 15587
      create  app/assets/stylesheets/foundation_emails.scss
      create  app/views/layouts/mailer.html.erb
```

The mailer.html.erb file is being created, but no content added. I think I've worked around this fine by going into your generator files and just copying out the mailer_layout template, but am curious what's causing this issue. I initially installed this gem via RubyGems, had this error, tried again using this repo and updating, but still no dice.

Thanks in advance for any help!

**Comment by erickreutz** [comment]
Getting this as well with a new project with Rails 5

**Comment by kball** [comment]
@zokioki I think you did the generator stuff... can you take a look?

**Comment by zokioki** [comment]
Just pushed out v1.3.7.2 - it should take care of this problem 👍
Let me know if it works for y'all.

**Comment by bartboy011** [comment]
That did the trick, thanks guys!
