### ISSUE TITLE
No LICENSE.txt

### ISSUE THREAD

**Issue by eckardt** [zurb/inky-rb#44]
Hi,

I would like to find out what license you are using for this project. Could you provide a `LICENSE.txt` within the repository (Similar as is done in https://github.com/zurb/foundation-rails)? That would make it much easier for people to figure out your license.

Best regards
Stephan

**Comment by marcandre** [comment]
Indeed, it's missing.

I imagine it's MIT, right @kball ?

**Comment by kball** [comment]
Yep, fixing...

**Comment by kball** [comment]
Fixed.

**Comment by eckardt** [comment]
Thanks!
