### ISSUE TITLE
Gem has no uninstall function

### ISSUE THREAD

**Issue by gbrl** [zurb/inky-rb#48]
Would be great to have an uninstall function for this gem.

**Comment by Deckluhm** [comment]
Not sure what you mean by "uninstall function" but:

- If you want to revert a `rails generate inky:install` command, just do: `rails destroy inky:install`
- If you want to uninstall the gem, just do: `gem uninstall inky-rb`

Note that these 2 commands work for any gem, it's not `inky-rb` specific:
- `rails destroy`: http://guides.rubyonrails.org/command_line.html#rails-destroy
- `gem uninstall`: http://guides.rubygems.org/command-reference#gem-uninstall

Hope it helps.

**Comment by gbrl** [comment]
Whoa! I did not know this! Thanks for explaining this.
