### ISSUE TITLE
HTML encoding is being forced to US-ASCII, causing transfer encoding issues down the line

### ISSUE THREAD

**Issue by jschwertfeger** [zurb/inky-rb#57]
Hi there,

I am using inky-rb in combination with premailer in our Rails setup. One of the things premailer does it to automatically create a plain text version of an email from the HTML variant, resulting in a multipart email.

I am not sure if it is in premailer or ActionMailer but somewhere a decision is being made if the plain text is just US-ASCII, in which case a 7bit content transfer encoding is fine, or if it something else, requiring a quoted-printable transfer encoding.

When using inky-rb I found that even though the HTML template specifies a UTF-8 encoding, the encoding is being forced to be US-ASCII in https://github.com/zurb/inky-rb/blob/develop/lib/inky.rb#L40, causing premailer (or ActionMailer) to not encode the plain text as quoted-printable, even when it should be.

I guess my question is, what is the purpose of that hardcoded US-ASCII encoding? Is this really needed?

-Jonas

**Comment by jschwertfeger** [comment]
@marcandre I believe you wrote that part? Any thoughts?

**Comment by marcandre** [comment]
Mmm, I remember that we had to switch to an HTML parser (XML being too strict), but can't remember why the encoding.
I wonder if any test fails if the encoding option is removed.

**Comment by marcandre** [comment]
PS: I'll have a look at this this coming week if noone else fixes it beforehand

**Comment by marcandre** [comment]
I pushed a branch which should, hopefully resolve your issue and work for anybody.

@jschwertfeger is it possible to test it for your purposes?

**Comment by jschwertfeger** [comment]
Seems to work for me. Thanks!
